### ISSUE TITLE
iron ore is called gold ore

### ISSUE THREAD

**Issue by spike11302000** [Codepixl/GLCraft#1]
when loading the game i see in the command promt

Registering Tile Gold Ore (6) <--this is iron ore btw
Registering Tile Gold Ore (7)

**Comment by Codepixl** [comment]
Oops! I’ll fix that.

On January 25, 2016 at 1:08:55 AM, spike11302000 (notifications@github.com) wrote:

when loading the game i see in the command promt

Registering Tile Gold Ore (6) <--this is iron ore btw
Registering Tile Gold Ore (7)

**Comment by spike11302000** [comment]
and btw your really good at this, i hope that you keep on working on the game

also im working on a mod loader for your game

**Comment by Codepixl** [comment]
That's funny, I'm working on an api too. Keep working on the mod loader though!

**Comment by spike11302000** [comment]
ok i will. but do you have any other form of communicating? like skype steam

**Comment by Codepixl** [comment]
Steam works, my username is Codepixl

**Comment by spike11302000** [comment]
ok i sent a request

**Comment by spike11302000** [comment]
im about done with my modloader but theres a few bugs here and there
