### ISSUE TITLE
New ideas...

### ISSUE THREAD

**Issue by IsaiahPatton** [Codepixl/GLCraft#14]
( To @Codepixl @spike11302000 )

Ideas I have for you:

* Hunger bar
* Chat
* Commands (/give, /setblock, /spawnmob)
* able to see your hand (to the right of the inv bar, like minecraft)
* save and quit to title (goes back to the title menu, and not close the whole game)
* mutiplayer
* creative mode
* more blocks (wool, clay, ...)
* bigger world
* wood names (all types of wood is right now called "Wood", not "Oak wood", "darkoak wood", ...)
* show version in title
* (This is for the launcher) add an version selecter to the launcher
* mobs (Zombie, skeleton, sheep, ...)
* add an todo.txt file
* new web site style, and new domain (www.glcraft.net)
* better plugin api
* users
* skins
* plugin list ( http://codepixl.net/GLCraft/plugins )
* anamated menu background

**Comment by Codepixl** [comment]
Thanks for the ideas! I'll just close the issue for now. I've actually been planning a lot of these now, but I'm not exactly sure how I'll implement them.
