### ISSUE TITLE
"Timed out"

### ISSUE THREAD

**Issue by IsaiahPatton** [Codepixl/GLCraft#18]
Sence you added the server, the game has been kicking me from my world saying "Timed out"

**Comment by Codepixl** [comment]
Make sure to sync to the latest commit and refresh the project. It should not be doing this, the only reason it will kick you for timing out is if your client doesn't respond to a ping within 10 seconds.

**Comment by Codepixl** [comment]
I actually started experiencing this issue recently. It *should* be fixed in the latest commit, but if it's not, reopen the issue.
