### ISSUE TITLE
"Timed Out"

### ISSUE THREAD

**Issue by IsaiahPatton** [Codepixl/GLCraft#20]
As soon as the world loads, I get kicked with "Timed Out",

If its possable you could make single player not autogen the server and have an button called "Broadcast online" button ingame

( #18 )

**Comment by IsaiahPatton** [comment]
on latest commit.

Created world on latest commit two.

tryed joining 3 times, and every time timed out

**Comment by IsaiahPatton** [comment]
[SERVER] New player logged in: Isaiah_Patton
[CLIENT] Done Receiving Chunks
[CLIENT] Kicked: Timed out
[SERVER] Player timed out: Isaiah_Patton
[SERVER] Closing server: The host was kicked.
Uncaught exception thrown in thread Server Thread
java.lang.NullPointerException
	at net.codepixl.GLCraft.network.Server.handlePacket(Server.java:256)
	at net.codepixl.GLCraft.network.Server$ConnectionRunnable.run(Server.java:312)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at net.codepixl.GLCraft.network.Server.handlePacket(Server.java:256)
	at net.codepixl.GLCraft.network.Server$ConnectionRunnable.run(Server.java:312)
	at java.lang.Thread.run(Thread.java:745)

AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by Codepixl** [comment]
Huh. Never gotten that error before. I'll try to fix it later when I have
time.

**Comment by spike11302000** [comment]
just make it not have a time out on singleplayer

**Comment by Codepixl** [comment]
That's a horrible workaround. Besides, it times out on multiplayer too.

**Comment by IsaiahPatton** [comment]
https://github.com/Codepixl/GLCraft/pull/21 <-- works fine

**Comment by Codepixl** [comment]
That will just disable kicking clients for timing out altogether - we still want the server to remove a player if something happens like their internet goes out or something.

**Comment by IsaiahPatton** [comment]
#22 <-- Does not disable kicking clients

**Comment by Codepixl** [comment]
It just elongates the timeout. Ten seconds is more than long enough. I will
actually try to find why this is happening instead of workarounds that will
probably break.

**Comment by spike11302000** [comment]
can't you have the client ping the server instead of the server ping the client?

**Comment by Codepixl** [comment]
Is this still happening to you in the latest commit? Try deleting the project, then re-cloning it in a different directory to make sure everything is up-to-date. I have not been getting kicked for timing out after leaving the game alone for extensive periods of time (1+ hours) even if I limit the speed of the game.

**Comment by Codepixl** [comment]
That's what it's doing; make sure to sync to the latest commit

**Comment by spike11302000** [comment]
every one dead?
