### ISSUE TITLE
Maven suport?

### ISSUE THREAD

**Issue by IsaiahPatton** [Codepixl/GLCraft#23]

**Comment by Codepixl** [comment]
I was thinking of using Maven, but what we have going now just kinda works. If I feel like trying that I might.

**Comment by IsaiahPatton** [comment]
All you need is an pom.xml

**Comment by Codepixl** [comment]
I'm aware how it works, I use it for some of my projects, I just don't see
any need for it right now.

**Comment by spike11302000** [comment]
What exacly is maven?

**Comment by Codepixl** [comment]
It's a system that helps manage project builds and libraries, but we don't
really need to use it.
