### ISSUE TITLE
Can't load 8x textures

### ISSUE THREAD

**Issue by IsaiahPatton** [Codepixl/GLCraft#27]
GLCraft won't load 8x images as textures (as Minecraft does).

**Comment by Codepixl** [comment]
Yes, that's because I don't have a system in place yet to load different sized textures. It is planned for the future!

**Comment by spike11302000** [comment]
if i have free time this weeken i can try to add 8x8,32x32,64x64 textures support

**Comment by Codepixl** [comment]
Nah it's fine I already have a system planned out for that (check my texturepacker repository)

**Comment by spike11302000** [comment]
ah ok

**Comment by spike11302000** [comment]
have you seen the game i have been making?
https://github.com/spike11302000/venture

**Comment by Codepixl** [comment]
Nice

**Comment by spike11302000** [comment]
I been working on for the past week or so
