### ISSUE TITLE
trees dont generate

### ISSUE THREAD

**Issue by spike11302000** [Codepixl/GLCraft#28]
also some more things
-dedicated server does not send chunk correctly
-a world hole somethings comes up (maybe check if chunk the is loaded every 10 seconds)
-place a door = crashed game

**Comment by Codepixl** [comment]
Yeah I know the chunks not sending correctly is because the server and client stop communicating for some reason

**Comment by spike11302000** [comment]
btw i just found out that i can open the glcraft in eclipse and it still works long as i dont commit the .classpath and .project file i should be able to use eclipse.
