### ISSUE TITLE
/time crash

### ISSUE THREAD

**Issue by Codepixl** [Codepixl/GLCraft#30]
Submitter: ElectrodeYT
Well, this is no fun. :(

GLCraft has crashed in thread: Thread[main,5,main]

NOTE: If you are launching this without the launcher from your desktop on Linux, it will not work. Use any other folder.

java.lang.NullPointerException
	at net.codepixl.GLCraft.GUI.GUIManager.input(GUIManager.java:146)
	at net.codepixl.GLCraft.world.CentralManager.input(CentralManager.java:193)
	at net.codepixl.GLCraft.world.CentralManager.update(CentralManager.java:657)
	at net.codepixl.GLCraft.GLCraft.update(GLCraft.java:368)
	at net.codepixl.GLCraft.GLCraft.commonInitializer(GLCraft.java:157)
	at net.codepixl.GLCraft.GLCraft.<init>(GLCraft.java:90)
	at net.codepixl.GLCraft.GLCraft.main(GLCraft.java:395)

Additional diagnostic information:
Max Memory Available to JVM: 1892MB
Total Memory Available to JVM: 141MB
Free Memory Available to JVM: 30MB
Operating System: Windows 10

--------------------------------
           LOG BELOW            
--------------------------------

[SILENT] Gathering System Info...

[SILENT] 	awt.toolkit = sun.awt.windows.WToolkit
[SILENT] 	file.encoding = Cp1252
[SILENT] 	file.encoding.pkg = sun.io
[SILENT] 	file.separator = \
[SILENT] 	java.awt.graphicsenv = sun.awt.Win32GraphicsEnvironment
[SILENT] 	java.awt.printerjob = sun.awt.windows.WPrinterJob
[SILENT] 	java.class.path = GLCraft.jar
[SILENT] 	java.class.version = 52.0
[SILENT] 	java.endorsed.dirs = C:\Program Files\Java\jre1.8.0_121\lib\endorsed
[SILENT] 	java.ext.dirs = C:\Program Files\Java\jre1.8.0_121\lib\ext;C:\Windows\Sun\Java\lib\ext
[SILENT] 	java.home = C:\Program Files\Java\jre1.8.0_121
[SILENT] 	java.io.tmpdir = C:\Users\ALEXAN~1\AppData\Local\Temp\
[SILENT] 	java.library.path = C:\Program Files\Java\jre1.8.0_121\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Users\Alexander\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\Alexander\AppData\Local\Programs\Python\Python36-32\;C:\Users\Alexander\AppData\Local\Microsoft\WindowsApps;;.
[SILENT] 	java.runtime.name = Java(TM) SE Runtime Environment
[SILENT] 	java.runtime.version = 1.8.0_121-b13
[SILENT] 	java.specification.name = Java Platform API Specification
[SILENT] 	java.specification.vendor = Oracle Corporation
[SILENT] 	java.specification.version = 1.8
[SILENT] 	java.vendor = Oracle Corporation
[SILENT] 	java.vendor.url = http://java.oracle.com/
[SILENT] 	java.vendor.url.bug = http://bugreport.sun.com/bugreport/
[SILENT] 	java.version = 1.8.0_121
[SILENT] 	java.vm.info = mixed mode
[SILENT] 	java.vm.name = Java HotSpot(TM) 64-Bit Server VM
[SILENT] 	java.vm.specification.name = Java Virtual Machine Specification
[SILENT] 	java.vm.specification.vendor = Oracle Corporation
[SILENT] 	java.vm.specification.version = 1.8
[SILENT] 	java.vm.vendor = Oracle Corporation
[SILENT] 	java.vm.version = 25.121-b13
[SILENT] 	os.arch = amd64
[SILENT] 	os.name = Windows 10
[SILENT] 	os.version = 10.0
[SILENT] 	path.separator = ;
[SILENT] 	sun.arch.data.model = 64
[SILENT] 	sun.awt.enableExtraMouseButtons = true
[SILENT] 	sun.boot.class.path = C:\Program Files\Java\jre1.8.0_121\lib\resources.jar;C:\Program Files\Java\jre1.8.0_121\lib\rt.jar;C:\Program Files\Java\jre1.8.0_121\lib\sunrsasign.jar;C:\Program Files\Java\jre1.8.0_121\lib\jsse.jar;C:\Program Files\Java\jre1.8.0_121\lib\jce.jar;C:\Program Files\Java\jre1.8.0_121\lib\charsets.jar;C:\Program Files\Java\jre1.8.0_121\lib\jfr.jar;C:\Program Files\Java\jre1.8.0_121\classes
[SILENT] 	sun.boot.library.path = C:\Program Files\Java\jre1.8.0_121\bin
[SILENT] 	sun.cpu.endian = little
[SILENT] 	sun.cpu.isalist = amd64
[SILENT] 	sun.desktop = windows
[SILENT] 	sun.font.fontmanager = null
[SILENT] 	sun.io.unicode.encoding = UnicodeLittle
[SILENT] 	sun.java.command = GLCraft.jar
[SILENT] 	sun.java.launcher = SUN_STANDARD
[SILENT] 	sun.jnu.encoding = Cp1252
[SILENT] 	sun.management.compiler = HotSpot 64-Bit Tiered Compilers
[SILENT] 	sun.os.patch.level = 
[SILENT] 	user.country = US
[SILENT] 	user.dir = C:\Users\Alexander\GLCraft\GLCraft
[SILENT] 	user.home = C:\Users\Alexander
[SILENT] 	user.language = en
[SILENT] 	user.name = Alexander
[SILENT] 	user.timezone = 
[SILENT] 

[GLCRAFT] Registering Tile Void (255)
[GLCRAFT] Registering Tile Air (0)
[GLCRAFT] Registering Tile Grass (1)
[GLCRAFT] Registering Tile Stone (2)
[GLCRAFT] Registering Tile Water (3)
[GLCRAFT] Registering Tile Glass (4)
[GLCRAFT] Registering Tile Coal Ore (5)
[GLCRAFT] Registering Tile Iron Ore (6)
[GLCRAFT] Registering Tile Gold Ore (7)
[GLCRAFT] Registering Tile Log (8)
[GLCRAFT] Registering Tile Leaves (9)
[GLCRAFT] Registering Tile Tall Grass (10)
[GLCRAFT] Registering Tile Lamp (11)
[GLCRAFT] Registering Tile Fire (12)
[GLCRAFT] Registering Tile Bluestone (13)
[GLCRAFT] Registering Tile Tnt (14)
[GLCRAFT] Registering Tile Lava (15)
[GLCRAFT] Registering Tile Wood (16)
[GLCRAFT] Registering Tile Sapling (17)
[GLCRAFT] Registering Tile Sand (18)
[GLCRAFT] Registering Tile Particle Projector (19)
[GLCRAFT] Registering Tile Workbench (20)
[GLCRAFT] Registering Tile Bedrock (21)
[GLCRAFT] Registering Tile Chest (22)
[GLCRAFT] Registering Tile Dirt (23)
[GLCRAFT] Registering Tile Furnace (24)
[GLCRAFT] Registering Tile Cobblestone (25)
[GLCRAFT] Registering Tile Bluestone Ore (26)
[GLCRAFT] Registering Tile Diamond Ore (27)
[GLCRAFT] Registering Tile Condensed Bluestone (28)
[GLCRAFT] Registering Tile Door (29)
---------------
[GLCRAFT] Registering Item Seeds (1)
[GLCRAFT] Registering Item Wooden Pickaxe (2)
[GLCRAFT] Registering Item Stone Pickaxe (3)
[GLCRAFT] Registering Item Stick (4)
[GLCRAFT] Registering Item Bucket (5)
[GLCRAFT] Registering Item Bucket of Water (6)
[GLCRAFT] Registering Item Iron Pickaxe (7)
[GLCRAFT] Registering Item Diamond (8)
[GLCRAFT] Registering Item Iron Ingot (9)
[GLCRAFT] Registering Item Coal (10)
[GLCRAFT] Registering Item Diamond Pickaxe (11)
[GLCRAFT] Registering Item Gold Pickaxe (12)
[GLCRAFT] Registering Item Gold Ingot (13)
[GLCRAFT] Registering Item Wooden Axe (14)
[GLCRAFT] Registering Item Stone Axe (15)
[GLCRAFT] Registering Item Iron Axe (16)
[GLCRAFT] Registering Item Gold Axe (17)
[GLCRAFT] Registering Item Diamond Axe (18)

I typed /time to see if there was a set command.

**Comment by electrodeyt** [comment]
Commenting here just so i get my email notifications on my report
