### ISSUE TITLE
Multiplayer issues

### ISSUE THREAD

**Issue by ramidzkh** [Codepixl/GLCraft#33]
Players look like stone pillars
No PvP
Packets are VERY spoofable (I could implement minecraft type server encryption*)

*Server has RSA keypair newly generated on boot
Client get them
Encrypts his public key and sends it to server
Both decide on key and IV
Use AES/CBC/NoPadding

**Comment by Codepixl** [comment]
I'm not working on GLCraft at the moment (and I don't know if I ever will keep working on it), but I am aware of these issues. I didn't have time or skill to model a player. Raycasting from entity to entity is not implemented, which is essential for PVP. And packets are spoofable, I believe I even mentioned so in the multiplayer video on my channel. I don't think that encryption is necessary (I don't think any games actually use encryption for anything except maybe chat), but if I ever get around to it I can definitely make packets less spoofable.
