### ISSUE TITLE
world loading not working

### ISSUE THREAD

**Issue by spike11302000** [Codepixl/GLCraft#5]
![world save glitch](https://cloud.githubusercontent.com/assets/12355526/18276575/1498a892-7411-11e6-965a-026c05b19262.PNG)

**Comment by Codepixl** [comment]
Did you make sure you're on the latest commit? If you are, send me the save you're trying to load (It will be in your home folder/GLCraft/saves/the save name)

**Comment by Codepixl** [comment]
Actually, I just tested it and it happened to me for some reason. Not sure why, because it used to work and I haven't changed how the world loads recently. I'll look into it.

**Comment by Codepixl** [comment]
Alright, I think I fixed it. Your old save won't work anymore, but all new saves should. Tell me if it works.

**Comment by spike11302000** [comment]
ok i was at school when i tested it so just have to wait

**Comment by spike11302000** [comment]
btw can you start working on plugins items?
