### ISSUE TITLE
just to chat

### ISSUE THREAD

**Issue by spike11302000** [Codepixl/GLCraft#6]
make it that you can delete the world saves in the menu

**Comment by spike11302000** [comment]
also if you can start working on plugin items and i will start adding some tiles like dirt

**Comment by Codepixl** [comment]
Let's use steam to chat

**Comment by Codepixl** [comment]
Hey let's just use steam to chat instead of GitHub

**Comment by spike11302000** [comment]
well i was at school

**Comment by spike11302000** [comment]
they wont let us install steam/games on the computers

**Comment by Codepixl** [comment]
Oh.
